# Generated by Django 3.2.5 on 2021-08-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='totat_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
